### ISSUE TITLE
Working progress for Android hardware acceleration

### ISSUE THREAD

**Issue by sk2212** [RSATom/QmlVlc#56] opened 2016-05-01 20:12 UTC
Hello RSATom,

something new from the Android frontage? It would help a lot of people if you get this last step also working!

Maybe you can create a donate for buying a Android device?

Regards

**Comment by RSATom** [comment] 2016-05-02 03:03
It's already working on android: https://play.google.com/store/apps/details?id=org.webchimera.desktop (sources: https://github.com/RSATom/WebChimera-desktop)

**Comment by sk2212** [comment] 2016-05-02 06:54
Hmm...the link does not work. I joined the tester program but it seems that the download url is broken.

Furthermore what are the changes between WebChimera and this QmlVlc project for Android? Where did you enable the hardware acceleration?

**Comment by RSATom** [comment] 2016-05-02 07:18
You could try again. Some times it doesn't open.

I do nothing with hardware acceleration, it works acceptable without it.

**Comment by sk2212** [comment] 2016-05-02 08:28
So it is the same like in QmlVlc project?

**Comment by RSATom** [comment] 2016-05-02 08:30
It uses QmlVlc as-is

**Comment by sk2212** [comment] 2016-05-02 08:32
Hmm, okay...on my Nexus 4 it is still not possible to play 1080p content without stuttering. With mzafers solution it works smoothly. So there must still something wrong or missing in QmlVlc.

**Comment by RSATom** [comment] 2016-05-02 08:33
maybe...

**Comment by RSATom** [comment] 2016-08-16 01:28
closed as duplicate of https://github.com/RSATom/QmlVlc/issues/29

**Closed by RSATom** 2016-08-16 01:28 UTC
